import Head from "next/head";
import Toolbar from "./components/Toolbar";
import ArticleFeed from "./components/ArticleFeed";
import styles from "../styles/Home.module.css";

const API_KEY_GUARDIAN = process.env.API_KEY_GUARDIAN;

export async function getServerSideProps() {
  const res = await fetch(
    `https://content.guardianapis.com/search?api-key=${API_KEY_GUARDIAN}`
  );
  const data = await res.json();
  return {
    props: {
      data: data,
    },
  };
}

export default function Home({ data }) {
  const articles = data.response.results;
  console.log(articles);
  return (
    <>
      <Head>
        \<title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />{" "}
      </Head>

      <div className="page-container">
        <Toolbar />
        <div className={styles.main}>
          <h1>The Guardian News App</h1>

          <ArticleFeed articles={articles} />
        </div>
      </div>
    </>
  );
}
